name: Deploy Website

on:
  push:
    branches:
      - shadrack
      # - main # Specify branch name
      
jobs:
  web-deploy:
    name: Deploying to Production
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER_T }}
          username: ${{ secrets.FTP_USERNAME_T }}
          password: ${{ secrets.FTP_PASSWORD_T` }}
          server-dir: '/'
          protocol: ftp
          passive: true
          port: 21
          local-dir: './'


